# Generated by Django 3.1.1 on 2020-09-20 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreFrontStatusLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online', models.BooleanField()),
                ('log_time', models.DateTimeField()),
                ('store_front', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.storefront')),
            ],
        ),
    ]
