# Generated by Django 3.1.1 on 2020-10-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stores', '0002_auto_20201007_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='address',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='phone',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
