# Generated by Django 3.1.1 on 2020-09-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_storefrontstatuslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='storefront',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
