# Generated by Django 3.1.1 on 2020-10-23 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_auto_20201007_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='friday',
        ),
        migrations.RemoveField(
            model_name='store',
            name='monday',
        ),
        migrations.RemoveField(
            model_name='store',
            name='saturday',
        ),
        migrations.RemoveField(
            model_name='store',
            name='sunday',
        ),
        migrations.RemoveField(
            model_name='store',
            name='thursday',
        ),
        migrations.RemoveField(
            model_name='store',
            name='tuesday',
        ),
        migrations.RemoveField(
            model_name='store',
            name='wednesday',
        ),
        migrations.CreateModel(
            name='DayOpeningOverride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('closed', models.BooleanField(default=False)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
            ],
            options={
                'unique_together': {('store', 'day')},
            },
        ),
    ]
