# Generated by Django 3.1.1 on 2020-09-24 22:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('offline_search_text',
                 models.CharField(help_text='Text to search on a store front page to see if it is offline.',
                                  max_length=100)),
            ],
        ),
    ]
